root : "../../input"
train_csv : "full_train.csv"
valid_csv : "full_valid.csv"
batch : 256
lr : 0.01
epoch : 50
num_classes : 6

seed : 42

output_path : "../../output/frame_classification"
output_dir : "full"
save_capacity : 5

wandb : True
wandb_project : "handwash"
wandb_entity : "cv4"
wandb_group : "full"
log_freq : 10

class_names : ["Step 1","Step 2","Step 3","Step 4","Step 5","Step 6"]